name = "bakeats"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "bakeats-orders"
database_id = "7b503236-74d8-4cab-9425-f46961f0bd2a"

[vars]
RAZORPAY_KEY_ID = "rzp_live_T0MmvVnomlNjE0"
FROM_EMAIL = "orders@bakeats.in"
MERCHANT_EMAIL = "orderbakeats@gmail.com"
SITE_URL = "https://bakeats.in"
